# == Schema Information
#
# Table name: movings
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  title         :string
#  description   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  move_type     :string
#  move_date     :date
#  dwelling_sqft :integer
#  dwelling_type :string
#  street_from   :string
#  city_from     :string
#  state_from    :string
#  zip_from      :string
#  street_to     :string
#  city_to       :string
#  state_to      :string
#  zip_to        :string
#  country_from  :string
#  country_to    :string
#

class Moving < ActiveRecord::Base

  belongs_to :user
  has_many :moving_items, dependent: :destroy

  has_many :moving_rooms, dependent: :destroy  # a join table
  has_many :rooms, through: :moving_rooms

  VALID_ZIP_REGEX = /\A[0-9]{5}(?:-[0-9]{4})?\z/

  validates :title,     presence: false,  length: { maximum: 50 }
  validates :move_type, presence: false
  validates :move_date, presence: false
  validates :dwelling_sqft, length: { maximum: 5 }, numericality: { only_integer: true }
  validates :dwelling_type, presence: false
  validates :street_from , length: { maximum: 50 }
  validates :street_to,    length: { maximum: 50 }
  validates :city_from,  presence: false, length: { maximum: 30 }
  validates :city_to,    presence: false, length: { maximum: 30 }
  validates :state_from, presence: false, length: { maximum: 30 }
  validates :state_to,   presence: false, length: { maximum: 30 }
  validates :zip_from, format: { with: VALID_ZIP_REGEX }, allow_blank: true
  validates :zip_to,   format: { with: VALID_ZIP_REGEX }, allow_blank: true
  validates :country_from , length: { maximum: 30 }
  validates :country_to,    length: { maximum: 30 }
  validates :description, length: { maximum: 255 }

  def save_rooms(room_ids)
    forgetAllRooms
    rememberRooms(reject_empty_options!(room_ids))
  end

  def autocomplete_suggestions
    {
      items:      Hash[Ingredient.pluck(:name, :volume)],
      rooms:      Room.select(:name).pluck(:name),
      categories: self.moving_items.select(:category).distinct.pluck(:category)
    }
  end

  private

    # Return number of rooms if rooms are successfully saved; else false.
    def rememberRooms(room_ids)
      room_ids.each do |room_id|
        result = MovingRoom.create(moving_id: self.id, room_id: room_id)
        return false if result.errors.any?
      end
      MovingRoom.where(moving_id: self.id).count
    end

    def forgetAllRooms
      MovingRoom.where(moving_id: self.id).destroy_all
    end

    # Remove an empty string generated by the hidden tag
    def reject_empty_options!(room_ids)
      room_ids = room_ids.reject!(&:empty?)
    end
end
